name=input("What is your name? ")
age=input("What is your age? ")
country=input("What is your country? ")
fav_food=input("What is your favourite food? ")
print("====Profile====")
print(f"Name       :  {name}")
print(f"Age        :  {age}")
print(f"Country    :  {country}")
print(f"Fav food   :  {fav_food}")
print("   Thanks for using my program  ")
